spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Отключаем автоматическое обнаружение
      routes:
        # Main Service - все маршруты напрямую
        - id: main_service_route
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/admin/**, /users/**, /public/**, /compilations/**, /events/**, /categories/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT,PATCH,DELETE

        # Stats Server
        - id: stats_service_route
          uri: lb://STATS-SERVER
          predicates:
            - Path=/hit, /stats/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

server:
  port: 8080