syntax = "proto3";

package telemetry.messages;

option java_multiple_files = true;
option java_package = "ru.practicum.telemetry.messages";

enum ActionType {
    ACTION_UNKNOWN = 0;
    ACTION_VIEW = 1;
    ACTION_REGISTER = 2;
    ACTION_LIKE = 3;
}

message UserAction {
    int64 user_id = 1;
    int64 event_id = 2;
    ActionType action_type = 3;
    string timestamp = 4;
}

message UserActionRequest {
    UserAction action = 1;
}

message UserActionResponse {
    bool success = 1;
    string message = 2;
}