services:
  postgres-main:
    image: postgres:15
    container_name: postgres-main
    environment:
      POSTGRES_DB: ewm-main-service
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "5433:5432"
    volumes:
      - postgres-main-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm -d ewm-main-service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network

  postgres-stats:
    image: postgres:15
    container_name: postgres-stats
    environment:
      POSTGRES_DB: ewm-stats-server
      POSTGRES_USER: postgres-ewm-stats-server
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres-stats-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres-ewm-stats-server -d ewm-stats-server"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network

  discovery-server:
    build:
      context: ./infra/discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ewm-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ewm-network:
    driver: bridge

volumes:
  postgres-main-data:
  postgres-stats-data: