-- Таблица комментариев (связывается с users и events)
CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    content    TEXT                                    NOT NULL,
    status     VARCHAR(20)                             NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Проверка допустимых значений статуса
    CONSTRAINT chk_comments_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- Индексы для оптимизации запросов
CREATE INDEX IF NOT EXISTS idx_comments_event_status ON comments (event_id, status);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_updated_at ON comments (updated_at DESC);


-- Таблица комментариев (связывается с users и events)
CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    content    TEXT                                    NOT NULL,
    status     VARCHAR(20)                             NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Внешние ключи (связь с существующими таблицами)
    CONSTRAINT fk_comments_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    -- Проверка допустимых значений статуса
    CONSTRAINT chk_comments_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- Индексы для оптимизации запросов
CREATE INDEX IF NOT EXISTS idx_comments_event_status ON comments (event_id, status);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_updated_at ON comments (updated_at DESC);