server:
  port: 0

spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/ewm-request-service
    username: ewm
    password: ewm

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"