-- Создание таблицы заявок на участие
CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT                      NOT NULL,
    requester_id BIGINT                      NOT NULL,
    status       VARCHAR(50)                 NOT NULL,

    CONSTRAINT uq_request_event_user UNIQUE (event_id, requester_id)
);

-- Индексы для оптимизации
CREATE INDEX IF NOT EXISTS idx_request_event_id ON request (event_id);
CREATE INDEX IF NOT EXISTS idx_request_requester_id ON request (requester_id);
CREATE INDEX IF NOT EXISTS idx_request_status ON request (status);