-- Создание таблицы заявок на участие
CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT                      NOT NULL,
    requester_id BIGINT                      NOT NULL,
    status       VARCHAR(50)                 NOT NULL,

    -- Внешние ключи
    CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_request_user FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT uq_request_event_user UNIQUE (event_id, requester_id)
);