spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # ==================== REQUEST SERVICE ====================
        - id: request_service_route
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/users/{userId}/requests/**, /public/events/{eventId}/requests/**, /internal/requests/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT,PATCH,DELETE

        # ==================== USER SERVICE ====================
        - id: user_service_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/admin/users/**, /public/users/**, /internal/users/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT,PATCH,DELETE

        # ==================== EVENT SERVICE ====================
        - id: event_service_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/events/**, /admin/categories/**, /admin/compilations/**, /events/**, /categories/**, /compilations/**, /users/{userId}/events/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT,PATCH,DELETE

        # ==================== COMMENT SERVICE ====================
        - id: comment_service_route
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/admin/comments/**, /events/{eventId}/comments/**, /users/{userId}/comments/**, /internal/comments/**, /comments/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT,PATCH,DELETE

        # ==================== STATS SERVICE ====================
        - id: stats_service_route
          uri: lb://STATS-SERVER
          predicates:
            - Path=/hit, /stats/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST

server:
  port: 8080

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always