spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: main_service_route
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/admin/**,/users/**,/public/**,/compilations/**,/events/**,/categories/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT,PATCH,DELETE

        - id: stats_service_route
          uri: lb://STATS-SERVER
          predicates:
            - Path=/hit,/stats/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST

server:
  port: 8080

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always