spring:
  application:
    name: aggregator

server:
  port: 0

grpc:
  client:
    analyzer-service:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: aggregator-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.practicum.avro.deserializer.UserActionDeserializer
    enable-auto-commit: false
    max-poll-records: 100

  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.practicum.avro.serializer.AvroSerializer
    acks: all
    retries: 3
    enable-idempotence: true
    linger.ms: 0
    compression-type: snappy
    request.timeout.ms: 60000
    delivery.timeout.ms: 180000

  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.practicum.aggregator: DEBUG
    org.springframework.kafka: INFO