spring:
  application:
    name: aggregator
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        max-attempts: 3
        max-interval: 6000

grpc:
  client:
    analyzer-service:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: aggregator-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: earliest
    enable-auto-commit: false
    max-poll-records: 100
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    retries: 3
    enable-idempotence: true
    batch-size: 16384
    linger-ms: 10
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

server:
  port: 0

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.practicum.aggregator: DEBUG
    org.springframework.kafka: INFO