--- Таблица категорий
CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

-- Создание локаций
CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    lat DECIMAL(8, 6)                           NOT NULL,
    lon DECIMAL(9, 6)                           NOT NULL
);

-- Создание событий
CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT REFERENCES categories (id)       NOT NULL,
    created_on         TIMESTAMP                               NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    event_date         TIMESTAMP                               NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT REFERENCES locations (id)        NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INT                                     NOT NULL DEFAULT 0,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN                                 NOT NULL DEFAULT TRUE,
    state              VARCHAR(12)                             NOT NULL DEFAULT 'PENDING',
    title              VARCHAR(120)                            NOT NULL,
    -- ✅ Добавлен REJECTED
    CONSTRAINT chk_event_state CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED', 'REJECTED'))
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_events_state ON events (state);
CREATE INDEX IF NOT EXISTS idx_events_category_id ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events (initiator_id);

-- Подборки
CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN      NOT NULL DEFAULT FALSE,
    title  VARCHAR(50)  NOT NULL
);

-- Связь Event-Compilation
CREATE TABLE IF NOT EXISTS event_compilation
(
    event_id       BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
    PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT fk_event_compilation_event
        FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_compilation_compilation
        FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE
);