syntax = "proto3";

package telemetry.services;

import "telemetry/messages/recommendations.proto";

option java_multiple_files = true;
option java_package = "ru.practicum.telemetry.services";

service AnalyzerController {
    rpc GetRecommendationsForUser (telemetry.messages.UserPredictionsRequest) returns (stream telemetry.messages.RecommendedEvent);
    rpc GetSimilarEvents (telemetry.messages.SimilarEventsRequest) returns (stream telemetry.messages.RecommendedEvent);
    rpc GetInteractionsCount (telemetry.messages.InteractionsCountRequest) returns (stream telemetry.messages.RecommendedEvent);
}