spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/analyzer_db
    username: analyzer_user
    password: analyzer_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analyzer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        specific.avro.reader: true
    listener:
      ack-mode: MANUAL_IMMEDIATE
      missing-topics-fatal: false

server:
  port: 0

grpc:
  server:
    port: 0

kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${server.port}"
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: localhost

logging:
  level:
    ru.practicum.analyzer: DEBUG