server:
  port: 0

spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/ewm-event-service
    username: ewm
    password: ewm

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10

# ===== НАСТРОЙКИ ДЛЯ gRPC КЛИЕНТОВ =====
grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
      maxInboundMessageSize: 10485760
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
      maxInboundMessageSize: 10485760

# ===== НАСТРОЙКИ ДЛЯ HTTP КЛИЕНТА СТАТИСТИКИ (оставляем для совместимости) =====
stat:
  service:
    id: stats-server

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"

# ===== ЛОГИРОВАНИЕ =====
logging:
  level:
    ru.practicum.grpc: DEBUG
    io.grpc: INFO